name: Test workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . -t fuzzy-search-v1.1

      - name: Run Docker container and test application
        run: |
          docker run -d -p 8000:8000 --name fuzzy-search-container fuzzy-search-v1.1
          sleep 10
          curl -f http://127.0.0.1:8000/ || { echo "Application did not start properly"; docker logs fuzzy-search-container; exit 1; }

      - name: Cleanup Docker container
        if: always()
        run: docker rm -f fuzzy-search-container
